"""Personal Assistant end-to-end pipeline orchestrator.

This module coordinates the complete voice interaction lifecycle:
1. Audio input ingestion and resampling.
2. OpenVINO Whisper Base INT8 speech-to-text transcription.
3. LM Studio local LLM conversational reasoning (token streaming).
4. Sentence-by-sentence chunking with abbreviation/decimal protection.
5. Kokoro-82M expressive speech synthesis pipelined concurrently with LLM generation.
6. Seamless sequential audio playback via StreamAudioPlayer.
"""

import asyncio
from collections import defaultdict, deque
from dataclasses import dataclass, field
import logging
import time
from typing import Any, AsyncGenerator, Callable, Deque, Dict, List, Optional, Tuple
import numpy as np

from app.config import settings
from app.core.audio import AudioProcessor, StreamAudioPlayer
from app.core.llm import LMStudioClient, split_into_sentence_chunks
from app.core.metrics import LatencyTracker
from app.core.sentences import SentenceBuffer, clean_text_for_speech
from app.core.stt import OpenVINOWhisperSTT
from app.core.tts import KokoroTTSEngine, QwenTTSEngine

logger = logging.getLogger(__name__)


@dataclass
class PipelineMetrics:
    """Execution timing metrics for individual pipeline stages.

    Attributes:
        stt_latency_ms: Milliseconds elapsed during speech transcription.
        llm_latency_ms: Wall-clock ms from first LLM token request to stream end.
        tts_latency_ms: Wall-clock ms from first TTS synth start to last synth end
            (overlaps LLM; llm+tts may exceed total due to pipelining).
        tts_synth_ms: Pure synthesis CPU time summed across sentences.
        ttfa_ms: Time-To-First-Audio (TTFA) in milliseconds.
        total_latency_ms: Total round-trip milliseconds.
        llm_ttft_ms: Time to first LLM token (T4-T3).
        sentence_latency_ms: First-sentence detection latency (T5-T4).
        voice_latency_ms: End-to-end mic-to-speaker latency (T8-T0).
        tokens_per_sec: LLM decode throughput.
        tts_realtime_factor: Audio seconds per synthesis second.
        audio_queue_depth: Ready-audio queue depth at turn end.
        system_ram_mb: Host RAM in use (MB).
        cpu_pct: Host CPU utilization percent.
        gpu_util_pct: GPU utilization percent (0 when unavailable).
        gpu_vram_mb: GPU VRAM in use (MB, 0 when unavailable).
        npu_status: NPU availability string.
    """

    stt_latency_ms: float = 0.0
    llm_latency_ms: float = 0.0
    tts_latency_ms: float = 0.0
    tts_synth_ms: float = 0.0
    ttfa_ms: float = 0.0
    total_latency_ms: float = 0.0
    # Detailed T0..T8 + resource telemetry (all optional, default 0).
    llm_ttft_ms: float = 0.0
    sentence_latency_ms: float = 0.0
    voice_latency_ms: float = 0.0
    tokens_per_sec: float = 0.0
    tts_realtime_factor: float = 0.0
    audio_queue_depth: int = 0
    system_ram_mb: float = 0.0
    cpu_pct: float = 0.0
    gpu_util_pct: float = 0.0
    gpu_vram_mb: float = 0.0
    npu_status: str = "unknown"


@dataclass
class AssistantStreamChunk:
    """Represents a single synthesized sentence audio chunk in a streaming response.

    Attributes:
        sentence_index: 0-based sequence index of the sentence.
        text: Sentence text string.
        audio_bytes: Synthesized WAV audio bytes for this sentence.
        sample_rate: Sample rate in Hz of the synthesized audio.
        is_final: True if this is the final sentence chunk.
    """

    sentence_index: int
    text: str
    audio_bytes: bytes
    sample_rate: int
    is_final: bool = False


@dataclass
class AssistantResponse:
    """Consolidated response object returned by the assistant pipeline.

    Attributes:
        user_text: Transcribed speech or input text from the user.
        assistant_text: Text response generated by the LM Studio LLM.
        audio_bytes: Synthesized WAV audio bytes for playback/download.
        sample_rate: Sample rate in Hz of the synthesized audio.
        metrics: Latency and execution metrics across components.
    """

    user_text: str
    assistant_text: str
    audio_bytes: bytes
    sample_rate: int
    metrics: PipelineMetrics = field(default_factory=PipelineMetrics)


def _is_mock(obj: Any) -> bool:
    """Returns True if obj is a unittest.mock instance (test doubles)."""
    try:
        from unittest.mock import Mock

        return isinstance(obj, Mock)
    except Exception:
        mod = type(obj).__module__ if hasattr(type(obj), "__module__") else ""
        return "mock" in str(mod).lower() or type(obj).__name__ == "MagicMock"


class AssistantPipeline:
    """High-level voice assistant orchestrator.

    Integrates OpenVINO Whisper STT, LM Studio streaming LLM, Kokoro TTS, and
    StreamAudioPlayer into a low-latency interaction pipeline.

    Thread-safety: histories are isolated per ``session_id`` and guarded by an
    asyncio lock. A shared global pipeline instance is safe for concurrent
    FastAPI/WebSocket requests as long as callers pass distinct session ids.
    """

    def __init__(
        self,
        stt_engine: Optional[OpenVINOWhisperSTT] = None,
        llm_client: Optional[LMStudioClient] = None,
        tts_engine: Optional[KokoroTTSEngine] = None,
    ) -> None:
        """Initializes the assistant pipeline with underlying subsystem engines.

        Args:
            stt_engine: OpenVINO Whisper STT instance.
            llm_client: LM Studio LLM client instance.
            tts_engine: Kokoro-82M TTS synthesizer instance.
        """
        self.stt = stt_engine or OpenVINOWhisperSTT()
        self.llm = llm_client or LMStudioClient()
        self.tts = tts_engine or KokoroTTSEngine()
        # Per-session bounded histories. Default session preserves the legacy
        # `conversation_history` list API used by routes/tests.
        self._histories: Dict[str, Deque[Dict[str, str]]] = defaultdict(deque)
        self._history_lock = asyncio.Lock()
        self._players: Dict[str, StreamAudioPlayer] = {}
        self._tts_sem = asyncio.Semaphore(max(1, getattr(settings, "tts_max_workers", 2)))
        self.last_metrics: PipelineMetrics = PipelineMetrics()
        # Per-session generation counters for user interruption/cancellation.
        # Each new turn bumps the counter; in-flight coroutines capture their
        # generation and abort when it no longer matches (barge-in).
        self._session_gen: Dict[str, int] = defaultdict(int)
        self._gen_lock = asyncio.Lock()
        # Live asyncio tasks per session so cancel() aborts blocked LLM awaits.
        self._session_tasks: Dict[str, set] = {}

    @property
    def conversation_history(self) -> List[Dict[str, str]]:
        """Legacy accessor for the default session history (mutable list)."""
        # deque is not a list; expose a list view that writes through.
        # For backward compat with direct .append() usage, keep an actual list
        # for the default session.
        if not hasattr(self, "_default_history"):
            self._default_history: List[Dict[str, str]] = []
        return self._default_history

    @conversation_history.setter
    def conversation_history(self, value: List[Dict[str, str]]) -> None:
        self._default_history = list(value)

    @property
    def _current_player(self) -> Optional[StreamAudioPlayer]:
        return self._players.get("default")

    @_current_player.setter
    def _current_player(self, value: Optional[StreamAudioPlayer]) -> None:
        if value is None:
            self._players.pop("default", None)
        else:
            self._players["default"] = value

    def _history_limit(self) -> int:
        turns = max(1, getattr(settings, "max_history_turns", 3))
        return turns * 2

    async def _get_history_slice(self, session_id: str) -> List[Dict[str, str]]:
        limit = self._history_limit()
        if session_id == "default" or session_id is None:
            hist = list(self.conversation_history)[-limit:]
            return hist
        async with self._history_lock:
            return list(self._histories.get(session_id, deque()))[-limit:]

    async def _append_history(self, session_id: str, user: str, assistant: str) -> None:
        limit = self._history_limit()
        if session_id == "default" or session_id is None:
            self.conversation_history.append({"role": "user", "content": user})
            self.conversation_history.append({"role": "assistant", "content": assistant})
            # Bound memory: keep last N turns + small headroom.
            del self.conversation_history[:-limit]
            return
        async with self._history_lock:
            dq = self._histories[session_id]
            dq.append({"role": "user", "content": user})
            dq.append({"role": "assistant", "content": assistant})
            while len(dq) > limit:
                dq.popleft()

    async def get_available_models(self) -> List[Dict[str, Any]]:
        """Retrieves available and running LLM models from LM Studio."""
        return await self.llm.list_available_models()

    async def set_model(self, model_id: str, load: bool = True) -> Dict[str, Any]:
        """Switches the active LLM model used by the assistant pipeline.

        Args:
            model_id: Identifier of the target LM Studio model.
            load: If True, attempts to preload the model into LM Studio memory.

        Returns:
            Dictionary with switch result and load status.
        """
        return await self.llm.set_model(model_id, load_into_memory=load)

    async def eject_model(self, model_id: Optional[str] = None) -> Dict[str, Any]:
        """Ejects a model or all models from LM Studio memory."""
        return await self.llm.eject_model(model_id)

    def set_tts_device(self, device: str) -> Dict[str, Any]:
        """Switches the Kokoro TTS compute processing unit (cpu or npu).

        Args:
            device: Target processing unit ('cpu' or 'npu').

        Returns:
            Dictionary describing the active device status.
        """
        return self.tts.set_device(device)

    def get_tts_device(self) -> Dict[str, Any]:
        """Returns the active Kokoro TTS compute processing unit details."""
        return self.tts.get_device_info()

    def warmup(self, warm_npu: Optional[bool] = None) -> None:
        """Pre-loads and compiles OpenVINO and TTS models for fast first response.

        Loads STT + TTS once, warms the LLM connection, and runs one tiny
        synthesis so the first user turn never pays graph-compile /
        voice-load costs. Cold-start (first compile) vs warm latency is
        logged: NPU encoder compile is one-time and cached on disk.

        Args:
            warm_npu: Eagerly compile the static NPU encoder now (slow
                startup, fast first turn). Defaults to
                settings.tts_warmup_npu. When False (default) the NPU
                encoder stays lazy and compiles on first synthesis.
        """
        from app.config import settings as _settings

        if warm_npu is None:
            warm_npu = bool(getattr(_settings, "tts_warmup_npu", False))
        logger.info("Starting pipeline warmup (warm_npu=%s)...", warm_npu)
        t0 = time.perf_counter()
        try:
            self.stt.load_model()
        except Exception as exc:
            logger.warning("STT warmup warning: %s", exc)

        try:
            self.tts.load_model()
        except Exception as exc:
            logger.warning("TTS warmup warning: %s", exc)

        if warm_npu:
            try:
                tn0 = time.perf_counter()
                on_npu = self.tts.warm_npu_encoder()
                logger.info(
                    "NPU encoder warmup: on_npu=%s in %.1fs.",
                    on_npu, time.perf_counter() - tn0,
                )
            except Exception as exc:
                logger.warning("NPU warmup warning: %s", exc)
        else:
            logger.info(
                "NPU encoder warmup deferred (TTS_WARMUP_NPU=false): first "
                "synthesis will pay one-time NPU compile (cached afterwards)."
            )

        try:
            self.llm.ensure_server_running()
        except Exception as exc:
            logger.warning("LLM warmup warning: %s", exc)

        # Tiny warm-up inferences so the first user turn never pays
        # graph-compile / voice-load / connection-pool costs.
        try:
            ts0 = time.perf_counter()
            self.tts.synthesize("Warmup complete.", speaker=None, language=None)
            logger.info(
                "TTS warm synth: %.1fms.", (time.perf_counter() - ts0) * 1000)
        except Exception as exc:
            logger.debug("TTS warmup synth note: %s", exc)

        logger.info(
            "Pipeline warmup completed in %.2fs (cold-start paid once).",
            time.perf_counter() - t0,
        )

    def _resolve_stream(self, prompt: str, history: List[Dict[str, str]]):
        """Returns an async-iterable of sentences, or None if not streamable."""
        fn = getattr(self.llm, "stream_sentence_chunks", None)
        if fn is None or not callable(fn):
            return None
        # Unwrap Mock side_effect case used in tests: patch.object(..., side_effect=...)
        # still yields a callable; calling it must produce an async iterable.
        try:
            stream = fn(prompt=prompt, history=history)
        except TypeError:
            try:
                stream = fn(prompt, history)
            except Exception:
                return None
        except Exception:
            return None
        if stream is None or _is_mock(stream):
            return None
        if hasattr(stream, "__aiter__"):
            return stream
        return None

    def _token_tap_stream(
        self,
        prompt: str,
        history: List[Dict[str, str]],
        on_token: Optional[Callable[[str], Any]],
    ):
        """Builds a token generator that forwards each raw LLM token onward.

        The same token stream feeds the sentence splitter for TTS, so text
        display (word-by-word) and speech synthesis stay driven by a single
        LLM inference pass.

        Args:
            prompt: User message prompt.
            history: Conversation history slice.
            on_token: Callback invoked with each raw token string.

        Returns:
            Async generator yielding raw LLM tokens, or None when the LLM
            client exposes no compatible token stream (e.g. test doubles).
        """
        fn = getattr(self.llm, "stream_response", None)
        if fn is None or not callable(fn) or _is_mock(fn):
            return None
        try:
            stream = fn(prompt=prompt, history=history)
        except TypeError:
            try:
                stream = fn(prompt, history)
            except Exception:
                return None
        except Exception:
            return None
        if stream is None or _is_mock(stream) or not hasattr(stream, "__aiter__"):
            return None

        async def _generate():
            async for token in stream:
                if not token:
                    continue
                if on_token is not None:
                    try:
                        if asyncio.iscoroutinefunction(on_token):
                            await on_token(token)
                        else:
                            on_token(token)
                    except Exception as cb_exc:
                        logger.warning("Token callback error: %s", cb_exc)
                yield token

        return _generate()

    async def _synthesize_one(
        self,
        sentence: str,
        speaker: Optional[str],
        language: Optional[str],
    ) -> Tuple[np.ndarray, int, float]:
        """Synthesizes one sentence with concurrency cap. Returns (audio, sr, synth_ms)."""
        async with self._tts_sem:
            t0 = time.perf_counter()
            audio_data, sr = await asyncio.to_thread(
                self.tts.synthesize,
                text=sentence,
                speaker=speaker,
                language=language,
            )
            synth_ms = (time.perf_counter() - t0) * 1000.0
        return audio_data, sr, synth_ms

    async def _emit_chunk(
        self,
        on_chunk: Optional[Callable[[AssistantStreamChunk], Any]],
        chunk: AssistantStreamChunk,
    ) -> None:
        if on_chunk is None:
            return
        try:
            if asyncio.iscoroutinefunction(on_chunk):
                await on_chunk(chunk)
            else:
                on_chunk(chunk)
        except Exception as cb_exc:
            logger.warning("Stream chunk callback error: %s", cb_exc)

    async def _next_generation(self, session_id: str) -> int:
        """Bumps and returns the generation counter for a session."""
        async with self._gen_lock:
            self._session_gen[session_id] += 1
            return self._session_gen[session_id]

    def _is_cancelled(self, session_id: str, gen: int) -> bool:
        """Returns True when a newer turn has superseded ``gen``."""
        return self._session_gen.get(session_id, gen) != gen

    def cancel(self, session_id: str = "default") -> None:
        """Interrupts any in-flight turn for ``session_id``.

        Stops LLM consumption (via generation check + task cancellation),
        drops pending TTS, clears the audio queue, and halts playback so a
        new user utterance can start immediately. Safe to call when idle.
        """
        self._session_gen[session_id] += 1
        player = self._players.pop(session_id, None)
        if player is not None:
            try:
                player.stop()
            except Exception:
                pass
        tasks = self._session_tasks.pop(session_id, set())
        for task in list(tasks):
            try:
                if not task.done():
                    task.cancel()
            except Exception:
                pass

    async def _execute_streaming_pipeline(
        self,
        prompt: str,
        speaker: Optional[str] = None,
        language: Optional[str] = None,
        play_audio: Optional[bool] = None,
        on_chunk: Optional[Callable[[AssistantStreamChunk], Any]] = None,
        on_token: Optional[Callable[[str], Any]] = None,
        session_id: str = "default",
    ) -> Tuple[str, bytes, int, PipelineMetrics]:
        """Core streaming executor: LM Studio tokens -> sentences -> Kokoro TTS -> playback.

        Overlaps LLM generation with TTS: each sentence is synthesized as soon as
        it completes, with up to ``tts_max_workers`` concurrent syntheses running
        while later tokens still stream. Results are emitted in sentence order so
        audio playback stays seamless.

        Args:
            prompt: User message prompt.
            speaker: Voice persona name.
            language: Language identifier.
            play_audio: Whether to play output audio on host device speakers.
            on_chunk: Optional callback invoked for each synthesized sentence chunk.
            on_token: Optional callback invoked for each raw LLM token as it
                arrives (drives word-by-word text display in clients).
            session_id: Session key for history isolation and player interruption.

        Returns:
            Tuple of (assistant_reply_text, wav_bytes, tts_sr, metrics).
        """
        # True-overlapped path (TTFA-optimized): producer/workers/emitter run
        # concurrently with bounded backpressure. See app/core/streaming.py.
        # Delegating here keeps one implementation for REST/WS/CLI callers.
        from app.core.streaming import run_streaming_pipeline as _run_overlapped

        return await _run_overlapped(
            self,
            prompt,
            speaker=speaker,
            language=language,
            play_audio=play_audio,
            on_chunk=on_chunk,
            on_token=on_token,
            session_id=session_id,
        )

    async def process_audio_bytes(
        self,
        audio_bytes: bytes,
        speaker: Optional[str] = None,
        language: Optional[str] = None,
        play_audio: Optional[bool] = None,
        on_chunk: Optional[Callable[[AssistantStreamChunk], Any]] = None,
        on_token: Optional[Callable[[str], Any]] = None,
        on_transcription: Optional[Callable[[str], Any]] = None,
        session_id: str = "default",
        tts_device: Optional[str] = None,
    ) -> AssistantResponse:
        """Executes the complete voice assistant loop from raw audio bytes.

        Flow:
            1. Decode audio bytes & resample to 16 kHz.
            2. Transcribe speech via OpenVINO Whisper Base INT8.
            3. Stream response tokens from LM Studio LLM.
            4. Chunk tokens into sentences with abbreviation protection.
            5. Hand over each sentence chunk to Kokoro-82M TTS concurrently.
            6. Play audio chunks sequentially via StreamAudioPlayer (if enabled).

        Args:
            audio_bytes: Input audio byte stream (WAV, MP3, WebM, etc.).
            speaker: Optional voice persona override for TTS.
            language: Optional language override.
            play_audio: Whether to play output audio on host device speakers.
            on_chunk: Optional callback invoked for each synthesized sentence chunk.
            on_token: Optional callback invoked for each raw LLM token as it
                arrives (drives word-by-word text display in clients).
            on_transcription: Optional callback invoked when STT finishes transcribing.
            session_id: Session key isolating conversation history/playback.
            tts_device: Optional compute processing unit override for Kokoro TTS ('cpu' or 'npu').

        Returns:
            AssistantResponse containing user text, assistant text, audio bytes, and metrics.
        """
        if tts_device is not None and str(tts_device).strip().lower() != str(self.tts.device).lower():
            try:
                self.set_tts_device(tts_device)
            except Exception as d_exc:
                logger.warning("Could not set TTS device '%s': %s", tts_device, d_exc)

        pipeline_start = time.perf_counter()
        t0_mic_end = pipeline_start  # T0 = user audio bytes ready
        t1_stt_start = 0.0  # T1 set below; T2 = Whisper done

        # Barge-in: silence any in-flight speech for this session immediately,
        # before paying STT cost, so the user never hears stale audio.
        try:
            _prev = self._players.get(session_id)
            if _prev is not None:
                _prev.stop()
        except Exception:
            pass

        # Step 1: Decode and resample audio
        audio_array, sample_rate = AudioProcessor.load_from_bytes(
            audio_bytes, target_sr=16000
        )

        # Step 2: OpenVINO Whisper Speech-To-Text (T1 -> T2)
        t1_stt_start = time.perf_counter()
        stt_start = t1_stt_start
        transcribed_text = await asyncio.to_thread(
            self.stt.transcribe, audio_array, sample_rate
        )
        stt_latency_ms = round((time.perf_counter() - stt_start) * 1000, 2)
        t2_stt_end = time.perf_counter()  # noqa: F841 (T2, surfaced via stt_latency_ms)

        if on_transcription is not None:
            try:
                if asyncio.iscoroutinefunction(on_transcription):
                    await on_transcription(transcribed_text)
                else:
                    on_transcription(transcribed_text)
            except Exception as tr_exc:
                logger.warning("Transcription callback warning: %s", tr_exc)

        if not transcribed_text:
            transcribed_text = "(No audible speech detected)"
            assistant_reply = "I didn't catch that. Could you please repeat?"
            audio_waveform, tts_sr = await asyncio.to_thread(
                self.tts.synthesize,
                text=assistant_reply,
                speaker=speaker,
                language=language,
            )
            wav_bytes = AudioProcessor.to_wav_bytes(audio_waveform, tts_sr)
            metrics = PipelineMetrics(
                stt_latency_ms=stt_latency_ms,
                llm_latency_ms=0.0,
                tts_latency_ms=0.0,
                ttfa_ms=stt_latency_ms,
                total_latency_ms=round(
                    (time.perf_counter() - pipeline_start) * 1000, 2
                ),
            )
            return AssistantResponse(
                user_text=transcribed_text,
                assistant_text=assistant_reply,
                audio_bytes=wav_bytes,
                sample_rate=tts_sr,
                metrics=metrics,
            )

        # Steps 3-6: Stream LLM -> Sentence Split -> Pipelined Kokoro TTS
        (
            assistant_reply,
            wav_bytes,
            tts_sr,
            metrics,
        ) = await self._execute_streaming_pipeline(
            prompt=transcribed_text,
            speaker=speaker,
            language=language,
            play_audio=play_audio,
            on_chunk=on_chunk,
            on_token=on_token,
            session_id=session_id,
        )

        metrics.stt_latency_ms = stt_latency_ms
        metrics.total_latency_ms = round(
            (time.perf_counter() - pipeline_start) * 1000, 2
        )
        # True mic-to-first-audio: STT + overlapped LLM/TTS TTFA. Voice latency
        # (T8-T0) equals this when playback is enabled; otherwise it marks
        # first-chunk readiness.
        try:
            metrics.ttfa_ms = round(stt_latency_ms + float(metrics.ttfa_ms), 2)
        except Exception:
            pass
        if not getattr(metrics, "voice_latency_ms", 0.0):
            metrics.voice_latency_ms = metrics.ttfa_ms
        else:
            try:
                metrics.voice_latency_ms = round(
                    stt_latency_ms + float(metrics.voice_latency_ms), 2
                )
            except Exception:
                metrics.voice_latency_ms = metrics.ttfa_ms

        logger.info(
            "Assistant cycle complete: User='%s' -> Bot='%s' [TTFA: %.1fms, Total: %.1fms]",
            transcribed_text,
            assistant_reply[:60],
            metrics.ttfa_ms,
            metrics.total_latency_ms,
        )

        return AssistantResponse(
            user_text=transcribed_text,
            assistant_text=assistant_reply,
            audio_bytes=wav_bytes,
            sample_rate=tts_sr,
            metrics=metrics,
        )

    async def process_text_prompt(
        self,
        prompt: str,
        speaker: Optional[str] = None,
        language: Optional[str] = None,
        play_audio: Optional[bool] = None,
        on_chunk: Optional[Callable[[AssistantStreamChunk], Any]] = None,
        on_token: Optional[Callable[[str], Any]] = None,
        session_id: str = "default",
    ) -> AssistantResponse:
        """Executes text-to-speech interaction bypassing STT.

        Streams tokens from LM Studio, chunks into sentences, hands each sentence
        to Kokoro-82M TTS with bounded concurrency, and plays audio sequentially.

        Args:
            prompt: Text prompt string.
            speaker: Voice persona name.
            language: Synthesis language code.
            play_audio: Whether to play output audio on speakers.
            on_chunk: Optional callback invoked for each synthesized sentence chunk.
            on_token: Optional callback invoked for each raw LLM token as it
                arrives (drives word-by-word text display in clients).
            session_id: Session key isolating conversation history/playback.

        Returns:
            AssistantResponse object with consolidated reply and metrics.
        """
        pipeline_start = time.perf_counter()

        (
            assistant_reply,
            wav_bytes,
            tts_sr,
            metrics,
        ) = await self._execute_streaming_pipeline(
            prompt=prompt,
            speaker=speaker,
            language=language,
            play_audio=play_audio,
            on_chunk=on_chunk,
            on_token=on_token,
            session_id=session_id,
        )

        metrics.total_latency_ms = round(
            (time.perf_counter() - pipeline_start) * 1000, 2
        )

        return AssistantResponse(
            user_text=prompt,
            assistant_text=assistant_reply,
            audio_bytes=wav_bytes,
            sample_rate=tts_sr,
            metrics=metrics,
        )

    async def process_direct_tts(
        self,
        text: str,
        speaker: Optional[str] = None,
        language: Optional[str] = None,
        play_audio: Optional[bool] = None,
        on_chunk: Optional[Callable[[AssistantStreamChunk], Any]] = None,
        session_id: str = "default",
        tts_device: Optional[str] = None,
    ) -> AssistantResponse:
        """Synthesizes text directly into speech bypassing STT transcription and LLM generation.

        Enables the pipeline to operate as a standalone, low-latency Text-to-Speech synthesizer.

        Args:
            text: Explicit text to synthesize into spoken audio.
            speaker: Optional voice persona override (e.g. 'af_heart', 'am_adam').
            language: Optional language code override (e.g. 'a', 'b').
            play_audio: Whether to play output audio on host device speakers.
            on_chunk: Optional callback invoked with the synthesized audio chunk.
            session_id: Session key isolating playback.
            tts_device: Optional compute processing unit override ('cpu' or 'npu').

        Returns:
            AssistantResponse containing the text, WAV audio bytes, and synthesis metrics.
        """
        if not text or not str(text).strip():
            raise ValueError("Input text cannot be empty for TTS synthesis.")

        if tts_device is not None and str(tts_device).strip().lower() != str(self.tts.device).lower():
            try:
                self.set_tts_device(tts_device)
            except Exception as d_exc:
                logger.warning("Could not set TTS device '%s': %s", tts_device, d_exc)

        pipeline_start = time.perf_counter()
        target_speaker = speaker or self.tts.speaker
        target_lang = language or self.tts.language

        cleaned = clean_text_for_speech(text)
        if not cleaned.strip():
            cleaned = text.strip()

        audio_data, sr = await asyncio.to_thread(
            self.tts.synthesize,
            cleaned,
            speaker=target_speaker,
            language=target_lang,
        )

        tts_wall_ms = round((time.perf_counter() - pipeline_start) * 1000.0, 2)
        wav_bytes = AudioProcessor.to_wav_bytes(audio_data, sr)

        chunk = AssistantStreamChunk(
            sentence_index=0,
            text=cleaned,
            audio_bytes=wav_bytes,
            sample_rate=sr,
            is_final=True,
        )
        if on_chunk is not None:
            await self._emit_chunk(on_chunk, chunk)

        should_play = play_audio if play_audio is not None else settings.auto_play_audio
        if should_play and len(audio_data) > 0:
            prev_player = self._players.pop(session_id, None)
            if prev_player is not None:
                try:
                    prev_player.stop()
                except Exception:
                    pass
            stream_player = AudioProcessor.create_stream_player(max_queue=2)
            self._players[session_id] = stream_player
            stream_player.enqueue(audio_data)
            stream_player.finish(wait=False)

        duration_sec = len(audio_data) / sr if sr > 0 else 0.0
        rtf = round(duration_sec / max(tts_wall_ms / 1000.0, 0.001), 2)
        metrics = PipelineMetrics(
            stt_latency_ms=0.0,
            llm_latency_ms=0.0,
            tts_latency_ms=tts_wall_ms,
            tts_synth_ms=tts_wall_ms,
            ttfa_ms=tts_wall_ms,
            total_latency_ms=tts_wall_ms,
            tts_realtime_factor=rtf,
            voice_latency_ms=tts_wall_ms,
        )
        self.last_metrics = metrics

        return AssistantResponse(
            user_text=text,
            assistant_text=cleaned,
            audio_bytes=wav_bytes,
            sample_rate=sr,
            metrics=metrics,
        )


    async def stream_text_prompt(
        self,
        prompt: str,
        speaker: Optional[str] = None,
        language: Optional[str] = None,
        play_audio: Optional[bool] = None,
        on_token: Optional[Callable[[str], Any]] = None,
        session_id: str = "default",
    ) -> AsyncGenerator[AssistantStreamChunk, None]:
        """Asynchronously streams synthesized sentence chunks as they are generated.

        Args:
            prompt: Text prompt string.
            speaker: Voice persona name.
            language: Synthesis language code.
            play_audio: Whether to play output audio on speakers.
            on_token: Optional callback invoked for each raw LLM token.
            session_id: Session key isolating conversation history/playback.

        Yields:
            AssistantStreamChunk containing each sentence's text and audio bytes.
        """
        queue: asyncio.Queue[Optional[AssistantStreamChunk]] = asyncio.Queue()

        async def _on_chunk(chunk: AssistantStreamChunk) -> None:
            await queue.put(chunk)

        async def _producer() -> None:
            try:
                await self.process_text_prompt(
                    prompt=prompt,
                    speaker=speaker,
                    language=language,
                    play_audio=play_audio,
                    on_chunk=_on_chunk,
                    on_token=on_token,
                    session_id=session_id,
                )
            finally:
                await queue.put(None)

        task = asyncio.create_task(_producer())
        try:
            while True:
                chunk = await queue.get()
                if chunk is None:
                    break
                yield chunk
        finally:
            await task

    def clear_history(self, session_id: Optional[str] = None) -> None:
        """Clears conversational history context.

        Args:
            session_id: If given, clears only that session; otherwise clears all.
        """
        # Cancelling first guarantees no stale turn appends history after clear.
        try:
            if session_id is None:
                for sid in list(self._session_gen.keys()):
                    self._session_gen[sid] += 1
            else:
                self._session_gen[session_id] += 1
        except Exception:
            pass
        if session_id is None or session_id == "default":
            if hasattr(self, "_default_history"):
                self._default_history.clear()
        if session_id is None:
            self._histories.clear()
            for player in list(self._players.values()):
                try:
                    player.stop()
                except Exception:
                    pass
            self._players.clear()
        elif session_id != "default":
            self._histories.pop(session_id, None)
            player = self._players.pop(session_id, None)
            if player is not None:
                try:
                    player.stop()
                except Exception:
                    pass
